#ifndef CRUISE_PLANNER_IDD
#define CRUISE_PLANNER_IDD 170430
#endif
#ifndef CRUISE_PLANNER_IDC_LIST
#define CRUISE_PLANNER_IDC_LIST 1704301
#endif
#ifndef CRUISE_PLANNER_IDC_MAP
#define CRUISE_PLANNER_IDC_MAP 1704302
#endif
#ifndef CRUISE_PLANNER_IDC_INFO
#define CRUISE_PLANNER_IDC_INFO 1704308
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_EASTING
#define CRUISE_PLANNER_IDC_TGT_EASTING 1704309
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_NORTHING
#define CRUISE_PLANNER_IDC_TGT_NORTHING 1704310
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_HEIGHT
#define CRUISE_PLANNER_IDC_TGT_HEIGHT 1704311
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_ANGLE
#define CRUISE_PLANNER_IDC_TGT_ANGLE 1704312
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_HEADING
#define CRUISE_PLANNER_IDC_TGT_HEADING 1704313
#endif
#ifndef CRUISE_PLANNER_IDC_CRUISE_MODE
#define CRUISE_PLANNER_IDC_CRUISE_MODE 1704316
#endif
