#ifndef CRUISE_PLANNER_IDD
#define CRUISE_PLANNER_IDD 170430
#endif
#ifndef CRUISE_PLANNER_IDC_LIST
#define CRUISE_PLANNER_IDC_LIST 1704301
#endif
#ifndef CRUISE_PLANNER_IDC_MAP
#define CRUISE_PLANNER_IDC_MAP 1704302
#endif
#ifndef CRUISE_PLANNER_IDC_INFO
#define CRUISE_PLANNER_IDC_INFO 1704308
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_EASTING
#define CRUISE_PLANNER_IDC_TGT_EASTING 1704309
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_NORTHING
#define CRUISE_PLANNER_IDC_TGT_NORTHING 1704310
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_HEIGHT
#define CRUISE_PLANNER_IDC_TGT_HEIGHT 1704311
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_ANGLE
#define CRUISE_PLANNER_IDC_TGT_ANGLE 1704312
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_HEADING
#define CRUISE_PLANNER_IDC_TGT_HEADING 1704313
#endif
#ifndef CRUISE_PLANNER_IDC_CRUISE_MODE
#define CRUISE_PLANNER_IDC_CRUISE_MODE 1704316
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_PREV
#define CRUISE_PLANNER_IDC_TGT_PREV 1704317
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_NEXT
#define CRUISE_PLANNER_IDC_TGT_NEXT 1704318
#endif
#ifndef CRUISE_PLANNER_IDC_TGT_LABEL
#define CRUISE_PLANNER_IDC_TGT_LABEL 1704319
#endif
#ifndef CRUISE_PLANNER_IDC_ADD_TGP
#define CRUISE_PLANNER_IDC_ADD_TGP 1704303
#endif
#ifndef CRUISE_PLANNER_IDC_ADD_MAP
#define CRUISE_PLANNER_IDC_ADD_MAP 1704304
#endif
#ifndef CRUISE_PLANNER_IDC_DELETE
#define CRUISE_PLANNER_IDC_DELETE 1704305
#endif
#ifndef CRUISE_PLANNER_IDC_MOVE_UP
#define CRUISE_PLANNER_IDC_MOVE_UP 1704306
#endif
#ifndef CRUISE_PLANNER_IDC_MOVE_DOWN
#define CRUISE_PLANNER_IDC_MOVE_DOWN 1704307
#endif
#ifndef CRUISE_PLANNER_IDC_SET_TGT_TGP
#define CRUISE_PLANNER_IDC_SET_TGT_TGP 1704314
#endif
#ifndef CRUISE_PLANNER_IDC_SET_TGT_MAP
#define CRUISE_PLANNER_IDC_SET_TGT_MAP 1704315
#endif
#ifndef CRUISE_PLANNER_IDC_MODE_TOO
#define CRUISE_PLANNER_IDC_MODE_TOO 1704320
#endif
#ifndef CRUISE_PLANNER_IDC_MODE_PP
#define CRUISE_PLANNER_IDC_MODE_PP 1704321
#endif
#ifndef CRUISE_PLANNER_IDC_CLEAR_ALL
#define CRUISE_PLANNER_IDC_CLEAR_ALL 1704322
#endif
